import os
from openai import OpenAI
import json
from dotenv import load_dotenv

import requests

load_dotenv()

client = OpenAI(base_url='https://k7uffyg03f.execute-api.us-east-1.amazonaws.com/prod/openai/v1', 
                api_key='any value',
                default_headers={"x-api-key": os.getenv('API_GATEWAY_KEY')})

# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_weather_api",
        "description": "Get today's weather for a specific location.",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "A location to get the weather for, e.g., 'Toronto' or 'Los Angeles'.",
                },
            },
            "required": ["location"],
        },
    },
]

def get_weather_api(location):
    print(f"Getting weather for {location}...")
    try:
        params = {
            'access_key': os.getenv('WEATHERSTACK_API_KEY'),
            'query': location
        }
        
        api_result = requests.get('https://api.weatherstack.com/current', params)
        api_response = api_result.json()
        
        # Extract weather data
       # weather = api_response.get('current', {})
        # print(weather)
        
        # if not weather:
        #     return "No weather data available at this time."
        
       
        # Summarize input to natural language
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "Transform flight information into a natural, and short summary of 50 words or less include the temperature, weather description, wind speed, and local time."},
                {"role": "user", "content": f"{api_response}\n\nUser question: {location}"}
            ]
        )
        
        return response.choices[0].message.content
    except Exception as e:
        return f"Error retrieving weather information: {str(e)}"


def get_weather(query, TONE):

    input_list = [
        {"role": "system", "content": TONE},
        {"role": "user", "content": query}
    ]

    # 2. Prompt the model with tools defined
    response = client.responses.create(
        model="gpt-4o",
        tools=tools,
        input=input_list,
    )

    # Save function call outputs for subsequent requests
    input_list += response.output

    for item in response.output:
        if item.type == "function_call":
            if item.name == "get_weather_api":
                # 3. Execute the function logic for get_weather_api
                args = json.loads(item.arguments)
                weather = get_weather_api(args['location'])  # Extract location string from dict
                
                # 4. Provide function call results to the model
                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({
                    "weather": weather
                    })
                })


    # print(get_weather_api("Toronto"))

    # print("Final input:")
    # print(input_list)

    response = client.responses.create(
        model="gpt-4o",
        instructions="Respond only with a weather report generated by a tool.",
        tools=tools,
        input=input_list,
    )

    return response.output_text  # Use .output_text for responses API

# # 5. The model should be able to give a response!
# print("Final output:")
# print(response.model_dump_json(indent=2))
# print("\n" + response.output_text)

# print(get_weather("What is the weather in Toronto today?"))